"""
Notion database schema snapshot.

Auto-generated by scripts/introspect_notion.py — do not edit by hand.
Re-run the script whenever Notion property definitions change.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# B2CLeads  —  32089024-cd3d-812e-a6c6-d8e21d9126b3
# ---------------------------------------------------------------------------

B2CLEADS_DB_ID = "32089024-cd3d-812e-a6c6-d8e21d9126b3"

class B2CLeadsProperties(BaseModel):
    """Typed properties for a B2CLeads Notion page.

    Field names are snake_case Python identifiers; aliases are the
    original Notion property names used in API responses.
    """
    model_config = {"populate_by_name": True}

    b2c_composite_score: object | None = Field(None, alias='B2C Composite Score')
    b2c_quality_gate: object | None = Field(None, alias='B2C Quality Gate')
    batch: list[str] = Field(default_factory=list, alias='Batch')
    call_script_opener: str | None = Field(None, alias='Call Script Opener')
    city_area: str | None = Field(None, alias='City / Area')
    data_confidence: Literal['High', 'Medium', 'Low'] | None = Field(None, alias='Data Confidence')
    date_added: str | None = Field(None, alias='Date Added')
    date_delivered: str | None = Field(None, alias='Date Delivered')
    dispute_reason: str | None = Field(None, alias='Dispute Reason')
    dispute_status: Literal['Pending', 'Accepted', 'Rejected by Client', 'Disputed'] | None = Field(None, alias='Dispute Status')
    email: str | None = Field(None, alias='Email')
    full_name: str = Field("", alias='Full Name')
    intent_date: str | None = Field(None, alias='Intent Date')
    intent_signal: str | None = Field(None, alias='Intent Signal')
    intent_source: Literal['Hellopeter', 'Gumtree', 'Facebook Group', 'MyBroadband', 'OLX', 'Twitter-X', 'Reddit', 'Other', 'Hellopeter (Netstar complaint)', 'Hellopeter (Tracker Connect complaint)', 'Hellopeter (Cartrack complaint)', 'Exa', 'Tavily', 'WhatsApp Outreach'] | None = Field(None, alias='Intent Source')
    intent_source_url: str | None = Field(None, alias='Intent Source URL')
    intent_strength: float | None = Field(None, alias='Intent Strength')
    person: list[str] = Field(default_factory=list, alias='Person')
    phone: str | None = Field(None, alias='Phone')
    province: Literal['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Free State', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape', 'Unknown', 'South Africa', 'SA', 'Cape Town'] | None = Field(None, alias='Province')
    qa_notes: str | None = Field(None, alias='QA Notes')
    qa_review_date: str | None = Field(None, alias='QA Review Date')
    rejection_deadline: object | None = Field(None, alias='Rejection Deadline')
    rejection_reason: Literal['Disconnected Number', 'Duplicate', 'No Interest Expressed', 'Invalid Contact', 'Out of Area', 'Other'] | None = Field(None, alias='Rejection Reason')
    sources_used: str | None = Field(None, alias='Sources Used')
    status: Literal['Pending QA', 'Pending Enrichment', 'QA Approved', 'QA Rejected', 'Sent to Call Centre', 'Contacted', 'Interested', 'Converted', 'Not Interested', 'Duplicate'] | None = Field(None, alias='Status')
    urgency_score: float | None = Field(None, alias='Urgency Score')
    vehicle_make_model: str | None = Field(None, alias='Vehicle Make / Model')
    vehicle_year: float | None = Field(None, alias='Vehicle Year')


# ---------------------------------------------------------------------------
# B2CBatches  —  32089024-cd3d-81a7-8691-ca999aa1494f
# ---------------------------------------------------------------------------

B2CBATCHES_DB_ID = "32089024-cd3d-81a7-8691-ca999aa1494f"

class B2CBatchesProperties(BaseModel):
    """Typed properties for a B2CBatches Notion page.

    Field names are snake_case Python identifiers; aliases are the
    original Notion property names used in API responses.
    """
    model_config = {"populate_by_name": True}

    api_cost_usd: float | None = Field(None, alias='API Cost (USD)')
    batch_id: str = Field("", alias='Batch ID')
    errors: str | None = Field(None, alias='Errors')
    leads_after_dedup: float | None = Field(None, alias='Leads After Dedup')
    leads_found: float | None = Field(None, alias='Leads Found')
    run_date: str | None = Field(None, alias='Run Date')
    sources_crawled: str | None = Field(None, alias='Sources Crawled')
    status: Literal['Running', 'Completed', 'Partial', 'Failed'] | None = Field(None, alias='Status')


# ---------------------------------------------------------------------------
# B2BLeads  —  30b89024-cd3d-810a-bb28-e46825320802
# ---------------------------------------------------------------------------

B2BLEADS_DB_ID = "30b89024-cd3d-810a-bb28-e46825320802"

class B2BLeadsProperties(BaseModel):
    """Typed properties for a B2BLeads Notion page.

    Field names are snake_case Python identifiers; aliases are the
    original Notion property names used in API responses.
    """
    model_config = {"populate_by_name": True}

    cipc_reg_number: str | None = Field(None, alias='CIPC Reg Number')
    call_centre_feedback: str | None = Field(None, alias='Call Centre Feedback')
    call_script_opener: str | None = Field(None, alias='Call Script Opener')
    city_area: str | None = Field(None, alias='City / Area')
    company_name: str = Field("", alias='Company Name')
    company_profile: str | None = Field(None, alias='Company Profile')
    composite_score: object | None = Field(None, alias='Composite Score')
    data_confidence: Literal['High', 'Medium', 'Low'] | None = Field(None, alias='Data Confidence')
    date_found: str | None = Field(None, alias='Date Found')
    date_sent: str | None = Field(None, alias='Date Sent')
    est_fleet_size: Literal['Small (1-5)', 'Medium (6-20)', 'Large (20+)', 'Unknown', 'Large (21+)'] | None = Field(None, alias='Est. Fleet Size')
    fleet_assessment: str | None = Field(None, alias='Fleet Assessment')
    fleet_likelihood: float | None = Field(None, alias='Fleet Likelihood')
    industry: Literal['Transport & Logistics', 'Construction', 'Agriculture', 'Food & Catering', 'Mining', 'Rental Services', 'Medical/Pharma', 'Government', 'Retail & Distribution', 'Services', 'Other', 'Courier & Delivery', 'Cold Chain / Food Distribution', 'Security Services'] | None = Field(None, alias='Industry')
    linkedin_url: str | None = Field(None, alias='LinkedIn URL')
    notes: str | None = Field(None, alias='Notes')
    prospect_summary: str | None = Field(None, alias='Prospect Summary')
    province: Literal['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Free State', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape'] | None = Field(None, alias='Province')
    public_contact: str | None = Field(None, alias='Public Contact')
    qa_notes: str | None = Field(None, alias='QA Notes')
    qa_review_date: str | None = Field(None, alias='QA Review Date')
    quality_gate: object | None = Field(None, alias='Quality Gate')
    rejection_reason: Literal['Incomplete profile', 'Already a customer', 'Not relevant industry', 'Too small', 'Out of service area', 'Poor data quality', 'Other'] | None = Field(None, alias='Rejection Reason')
    segment: Literal['B2B', 'B2C'] | None = Field(None, alias='Segment')
    sources_used: str | None = Field(None, alias='Sources Used')
    status: Literal['Pending QA', 'QA Approved', 'QA Rejected', 'Sent to Call Centre', 'Contacted', 'Interested', 'Converted', 'Not Interested', 'Duplicate'] | None = Field(None, alias='Status')
    tracking_need_reasoning: str | None = Field(None, alias='Tracking Need Reasoning')
    tracking_need_score: float | None = Field(None, alias='Tracking Need Score')
    website: str | None = Field(None, alias='Website')


# ---------------------------------------------------------------------------
# Sources  —  30b89024-cd3d-81b1-ab3a-c900965b5d64
# ---------------------------------------------------------------------------

SOURCES_DB_ID = "30b89024-cd3d-81b1-ab3a-c900965b5d64"

class SourcesProperties(BaseModel):
    """Typed properties for a Sources Notion page.

    Field names are snake_case Python identifiers; aliases are the
    original Notion property names used in API responses.
    """
    model_config = {"populate_by_name": True}

    last_crawled: str | None = Field(None, alias='Last Crawled')
    notes: str | None = Field(None, alias='Notes')
    popia_status: Literal['Compliant', 'Caution Required', 'Blocked'] | None = Field(None, alias='POPIA Status')
    source_name: str = Field("", alias='Source Name')
    source_type: Literal['Government Register', 'Tender Portal', 'Business Directory', 'Social Media', 'Crime Stats', 'Other'] | None = Field(None, alias='Source Type')
    status: Literal['Active', 'Paused', 'Broken', 'Deprecated'] | None = Field(None, alias='Status')
    url: str | None = Field(None, alias='URL')


# ---------------------------------------------------------------------------
# ClaireProspects  —  34189024-cd3d-8108-bd69-ce41ebfa2eb2
# ---------------------------------------------------------------------------

CLAIREPROSPECTS_DB_ID = "34189024-cd3d-8108-bd69-ce41ebfa2eb2"

class ClaireProspectsProperties(BaseModel):
    """Typed properties for a ClaireProspects Notion page.

    Field names are snake_case Python identifiers; aliases are the
    original Notion property names used in API responses.
    """
    model_config = {"populate_by_name": True}

    business: str | None = Field(None, alias='Business')
    date_added: str | None = Field(None, alias='Date Added')
    email: str | None = Field(None, alias='Email')
    full_name: str = Field("", alias='Full Name')
    motivation: str | None = Field(None, alias='Motivation')
    outreach_message: str | None = Field(None, alias='Outreach Message')
    outreach_sent_at: str | None = Field(None, alias='Outreach Sent At')
    phone: str | None = Field(None, alias='Phone')
    response: str | None = Field(None, alias='Response')
    response_at: str | None = Field(None, alias='Response At')
    response_status: Literal['Pending', 'Yes', 'No', 'Maybe', 'No Reply'] | None = Field(None, alias='Response Status')
    submitted_to_pipeline: bool = Field(False, alias='Submitted to Pipeline')


# ---------------------------------------------------------------------------
# All DB IDs — import this dict in client.py for iteration
# ---------------------------------------------------------------------------

ALL_DB_IDS: dict[str, str] = {
    "B2CLeads": B2CLEADS_DB_ID,
    "B2CBatches": B2CBATCHES_DB_ID,
    "B2BLeads": B2BLEADS_DB_ID,
    "Sources": SOURCES_DB_ID,
    "ClaireProspects": CLAIREPROSPECTS_DB_ID,
}
